version: '3.8'
services:
  micronautbase:
    image: 'micronautbase'
    container_name: micronautbase
    ports:
      - '8080:8080'
    environment:
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
      - DATABASE_URL=jdbc:mysql://172.28.0.2:3306/base
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_GENERATE=NONE
      - DATABASE_DIALECT=MYSQL